import { UIApplication } from 'UIKit'
import { URL } from 'Foundation'
import { OpenSchema, CanOpenURL } from '../interface.uts'

export const openSchema : OpenSchema = function (url : string) : void {
  if (!canOpenURL(url)) {
    return
  }
  let uri = new URL(string = url)
  UIApplication.shared.open(uri!)
}

export const canOpenURL : CanOpenURL = function (url : string) : boolean {
  if (url.length > 0) {
    let uri = new URL(string = url)
    if (uri != null && UIApplication.shared.canOpenURL(uri!)) {
      return true
    }
  }
  return false
}
