import { normalizeInitOptions } from './common/config.uts'
import { GioTracker } from './common/core/tracker.uts'

const tracker = GioTracker.getInstance()

export const init = function (options : UTSJSONObject) : boolean {
  return tracker.init(normalizeInitOptions(options))
}

export function track(eventName : string, properties : UTSJSONObject | null = null) : boolean {
  return tracker.track(eventName, properties)
}

export function setUserId(userId : string, userKey : string | null = null) : boolean {
  return tracker.setUserId(userId, userKey)
}

export const setUserAttributes = function (userAttributes : UTSJSONObject | null) : boolean {
  return tracker.setUserAttributes(userAttributes)
}

export const identify = function (assignmentId : string | number) : boolean {
  return tracker.identify(assignmentId)
}

export const clearUserId = function () : boolean {
  return tracker.clearUserId()
}

export const setUserKey = function (userKey : string) : boolean {
  return tracker.setUserKey(userKey)
}

export const registerPlugins = function (plugins : Array<any>) : boolean {
  return tracker.registerPlugins(plugins)
}

export const getABTest = function (
  layerId : string | number,
  callback : ((result : any) => void) | null = null
) : boolean {
  return tracker.getABTest(layerId, callback)
}
