export type GioReportSuccess = {
  errMsg : string
}

export type GioReportErrorCode =
  62000 |
  62001 |
  62002 |
  62003

export type GioReportError = {
  errCode : GioReportErrorCode
  errMsg : string
  message : string
  name : string
}

export type GioReportFail = GioReportError
export type GioReportSuccessCallback = (res : GioReportSuccess) => void
export type GioReportFailCallback = (err : GioReportFail) => void
export type GioReportCompleteCallback = (res : any) => void

export type GioInitOptions = {
  projectId : string
  dataSourceId : string
  appId : string
  serverUrl : string
  appVersion : string | null
  cookieDomain : string | null
  debug : boolean | null
  forceLogin : boolean | null
  originalSource : boolean | null
  storageType : string | null
  sessionExpires : number | null
}

export type GioPluginItem = {
  name : string
  options : UTSJSONObject | null
}

export type GioABTestPluginOptions = {
  abServerUrl : string | null
  requestInterval : number | null
  requestTimeout : number | null
}

export type GioABTestResult = {
  layerId : string
  strategyId : string
  experimentId : string
  layerName : string | null
  experimentName : string | null
  strategyName : string | null
  variables : UTSJSONObject | null
}

export type GioABTestCallback = (result : GioABTestResult | UTSJSONObject) => void

export type GioContext = {
  deviceId : string
  sessionId : string
  userId : string | null
  userKey : string | null
}

export type GioPageContext = {
  path : string
  query : string | null
  title : string | null
  referralPage : string | null
  duration : number | null
}

export type GioOriginalSource = {
  sessionId : string
  path : string
  query : string
  title : string
  referralPage : string
}

export type GioTrackEvent = {
  appChannel : string | null
  appVersion : string
  dataSourceId : string
  deviceBrand : string
  deviceId : string
  deviceModel : string | null
  deviceType : string | null
  domain : string
  eventName : string | null
  eventSequenceId : number | null
  eventType : string
  language : string
  latitude : number | null
  longitude : number | null
  networkState : string | null
  operatingSystem : string | null
  path : string | null
  platform : string
  platformVersion : string
  query : string | null
  referralPage : string | null
  screenHeight : number
  screenWidth : number
  sdkVersion : string
  sessionId : string
  timestamp : number
  timezoneOffset : number
  title : string
  userId : string | null
  userKey : string | null
  attributes : UTSJSONObject | null
}
