// Android App 端系统字段解析器。
import {
  GioSystemContextFields,
  GioSystemContextResolver
} from '../interface.uts'

class AppAndroidSystemContextResolver implements GioSystemContextResolver {
  // ​​warning: The corresponding parameter in the supertype 'GioSystemContextResolver' is named 'systemInfo'. This may cause problems when calling this function with named arguments.​
  // 实现的方法参数名与interface不一致，如果使用命名参数调用会出现不一致
  resolveSystemContext(
    systemInfo : any | null,
    osName : string,
    osLabel : string,
    version : string,
    deviceBrand : string,
    deviceType : string
  ) : GioSystemContextFields | null {
    return {
      deviceBrand: deviceBrand,
      deviceType: deviceType,
      operatingSystem: osLabel,
      platform: osLabel,
      platformVersion: version.length > 0 ? version : osLabel
    } as GioSystemContextFields
  }
}

export function createAppAndroidSystemContextResolver() : GioSystemContextResolver {
  return new AppAndroidSystemContextResolver()
}
