// 本文件为自动构建生成
  export {
    GetLocationFailImpl,
  UniLocationProvider,
  LocationErrorCode,
  IGetLocationFail,
  GetLocationFail,
  GetLocation,
  GetLocationSuccess,
  GetLocationOptions,
  StartLocationUpdateSuccess,
  StartLocationUpdateOptionsType,
  StartLocationUpdateOptions,
  StartLocationUpdate,
  StopLocationUpdateSuccess,
  StopLocationUpdateOptions,
  StopLocationUpdate,
  OnLocationChangeResult,
  OnLocationChangeCallback,
  OnLocationChange,
  OffLocationChange,
  OnLocationChangeErrorCallback,
  OnLocationChangeError,
  OffLocationChangeError,
  StartLocationUpdateBackgroundSuccess,
  StartLocationUpdateBackgroundOptionsType,
  StartLocationUpdateBackgroundOptions,
  StartLocationUpdateBackground,
  } from './interface'
  